# Generated by Django 3.2.12 on 2022-03-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220225_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
