# Generated by Django 3.2.12 on 2022-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220314_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='created_at',
            field=models.DateField(auto_now_add=True, default="2022-03-18"),
            preserve_default=False,
        ),
    ]
