# Generated by Django 3.2.12 on 2022-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_internship_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
