# Generated by Django 3.2.12 on 2022-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220318_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
