# Generated by Django 3.2.12 on 2022-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
