# Generated by Django 3.2.12 on 2022-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_internship_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='liked',
            field=models.ManyToManyField(to='base.Student'),
        ),
    ]
