# Generated by Django 3.2.12 on 2022-03-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_internship_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='liked',
        ),
        migrations.AddField(
            model_name='student',
            name='liked_int',
            field=models.ManyToManyField(to='base.Internship'),
        ),
    ]
