# Generated by Django 3.2.12 on 2022-03-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_internshiplike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiplike',
            name='user',
        ),
        migrations.AddField(
            model_name='internshiplike',
            name='student',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
            preserve_default=False,
        ),
    ]
