export const CLIENT_USER_LOADED = "CLIENT_USER_LOADED";
export const CLIENT_USER_FAILED = "CLIENT_USER_FAILED";
export const FREELANCE_USER_LOADED = "FREELANCE_USER_LOADED";
export const FREELANCE_USER_FAILED = "FREELANCE_USER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FUSER_SUCCESS = "REGISTER_FUSER_SUCCESS";
export const REGISTER_FUSER_FAILED = "REGISTER_FUSER_FAILED";
export const REGISTER_CUSER_SUCCESS = "REGISTER_CUSER_SUCCESS";
export const REGISTER_CUSER_FAILED = "REGISTER_CUSER_FAILED";

export const INTERNSHIP_LIST_LOADED = "INTERNSHIP_LIST_LOADED";
export const INTERNSHIP_LIST_FAILED = "INTERNSHIP_LIST_FAILED";

export const GET_INTERNSHIPS_BEGIN = "GET_INTERNSHIPS_BEGIN";
export const GET_INTERNSHIPS_SUCCESS = "GET_INTERNSHIPS_SUCCESS";
export const GET_INTERNSHIPS_ERROR = "GET_INTERNSHIPS_ERROR";
export const GET_SINGLE_INTERNSHIP_BEGIN = "GET_SINGLE_INTERNSHIP_BEGIN";
export const GET_SINGLE_INTERNSHIP_SUCCESS = "GET_SINGLE_INTERNSHIP_SUCCESS";
export const GET_SINGLE_INTERNSHIP_ERROR = "GET_SINGLE_INTERNSHIP_ERROR";

export const LOAD_INTERNSHIPS = "LOAD_INTERNSHIPS";
export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_INTERNSHIPS = "SORT_INTERNSHIPS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_INTERNSHIPS = "FILTER_INTERNSHIPS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const EDIT_COMPANY_IMAGE = "EDIT_COMPANY_IMAGE";
export const EDIT_COMPANY_ADDR = "EDIT_COMPANY_ADDR";
export const EDIT_COMPANY_DESC = "EDIT_COMPANY_DESC";
export const EDIT_COMPANY_NAME = "EDIT_COMPANY_NAME";

export const GET_SINGLE_COMPANY_SUCCESS = "GET_SINGLE_COMPANY_SUCCESS";
export const GET_SINGLE_COMPANY_ERROR = "GET_SINGLE_COMPANY_ERROR";
export const GET_SINGLE_COMPANY_BEGIN = "GET_SINGLE_COMPANY_BEGIN";

export const GET_SINGLE_STUDENT_SUCCESS = "GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_ERROR = "GET_SINGLE_STUDENT_ERROR";
export const GET_SINGLE_STUDENT_BEGIN = "GET_SINGLE_STUDENT_BEGIN";
export const EDIT_STUDENT_ADDR = "EDIT_STUDENT_ADDR";
export const EDIT_STUDENT_DESC = "EDIT_STUDENT_DESC";

export const ADD_INTERNSHIP_LIKE = "ADD_INTERNSHIP_LIKE";
export const REMOVE_INTERNSHIP_LIKE = "REMOVE_INTERNSHIP_LIKE";
