# Generated by Django 4.0.1 on 2022-04-26 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('universityName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('major', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('cGpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('img', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
